# name = "COM1"
[serial]
name = "COM1"
baud = 9600
read_timeout = 500
size = 8
parity = "N"
stop_bits = 1
flow_control = "none"
buffer_size = 1024

[nats]
url = "nats://localhost:4222"
username = "client_user"
password = "client_password"
subject = "telegram"

[telegram]
end_tag = "NNNN"
seq_tag = "ZCZC\\s(\\S+)\\s"
