[serial]
name = "../dev/ttyV0"
baud = 9600
read_timeout = 500
size = 8
parity = "N"
stop_bits = 1
flow_control = "none"
buffer_size = 1024

[nats]
urls = "nats://localhost:4222"
username = "client_user"
password = "client_password"
subject = "Telegram.Serial"
cluster_id = "test-cluster"
client_id = "serial-client"

[telegram]
end_tag = "NNNN"
seq_tag = "ZCZC\\s(\\S+)\\s"
pattern_split = "(?s)ZCZC.*?NNNN"
